[users.temporus]
voice_name = "Microsoft Server Speech Text to Speech Voice (sv-SE, MattiasNeural)"
audio_format = "audio-24khz-48kbitrate-mono-mp3"
pitch = 0
rate = 30
volume = 0

[users.rwxito]
voice_name = "Microsoft Server Speech Text to Speech Voice (en-US, AnaNeural)"
audio_format = "audio-24khz-48kbitrate-mono-mp3"
pitch = 0
rate = 30
volume = 0

[users.icsboyx]
voice_name = "Microsoft Server Speech Text to Speech Voice (it-IT, DiegoNeural)"
audio_format = "audio-24khz-48kbitrate-mono-mp3"
pitch = 0
rate = 30
volume = 0

[users.cascian08]
voice_name = "Microsoft Server Speech Text to Speech Voice (de-DE, KillianNeural)"
audio_format = "audio-24khz-48kbitrate-mono-mp3"
pitch = 0
rate = 30
volume = 0

[users.togglebit]
voice_name = "Microsoft Server Speech Text to Speech Voice (cs-CZ, VlastaNeural)"
audio_format = "audio-24khz-48kbitrate-mono-mp3"
pitch = 0
rate = 30
volume = 0

[users.motenay]
voice_name = "Microsoft Server Speech Text to Speech Voice (fr-CH, FabriceNeural)"
audio_format = "audio-24khz-48kbitrate-mono-mp3"
pitch = 0
rate = 30
volume = 0

[users.knekkebjoern]
voice_name = "Microsoft Server Speech Text to Speech Voice (en-GB, MaisieNeural)"
audio_format = "audio-24khz-48kbitrate-mono-mp3"
pitch = 0
rate = 30
volume = 0
